server:
  port: 8081

springdoc:
  swagger-ui:
    path: apidoc.html
  version: v1
  paths-to-match:
    - /**
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
